{
 "title": "Chia Dashboard",
 "description": "Chia Dashboard",
 "time": { "from": "2021-10-21T07:09:43.000Z", "to": "2021-11-29T14:56:49.345Z" },
 "templating": {
  "list": [
   {
    "name": "host_name",
    "label": "主机",
    "query": "SHOW TAG VALUES  ON  \"chia_monitor\" FROM \"chia_log_monitor\" WITH KEY =\"host\""
   },
   {
    "name": "plot_path",
    "label": "路径",
    "query": "SHOW TAG VALUES  ON  \"chia_monitor\" FROM \"chia_log_monitor\" WITH KEY =\"plot_path\" WHERE \"host\"=~ /^$host_name$/ and plot_path <> '-'"
   },
   { "name": "text_tiltle_size", "query": "20" },
   { "name": "text_value_size", "query": "28" }
  ]
 },
 "panels": [
  {
   "title": "收割机列表  ( 单位：田数 )",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_ip",
     "query": "select last(plotsCount) as count , ip from chia_harvester_monitor where  time > now() - 1d group by ip "
    },
    {
     "alias": "总容量",
     "query": "select last(plotCountForAllHarvesters) from chia_farm_summary_monitor "
    }
   ]
  },
  {
   "title": "全网容量 (EiB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select estimatedNetworkSpace from chia_farm_summary_monitor  where time > now()  - 60d"
    }
   ]
  },
  {
   "title": "预计爆块时间 (天)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select expectedTimeToWin from chia_farm_summary_monitor where time > now()  - 60d"
    }
   ]
  },
  {
   "title": "用户交易费用",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select userTransactionFees from chia_farm_summary_monitor  where time > now()  - 60d"
    }
   ]
  },
  {
   "title": "耕种收益",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select totalChiaFarmed from chia_farm_summary_monitor  where time > now()  - 60d"
    }
   ]
  },
  {
   "title": "每日报警次数监控",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "select count(counter) from chia_log_monitor  where time > now() - 60d group by \"host\", time(1d);"
    }
   ]
  },
  {
   "title": "主节点日志监控",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "SELECT msg, node, \"host\", logger, level, plot_path, plot_name, counter FROM \"chia_log_monitor\"  where node <> 'harvester' and time > now() - 60d order by time desc limit 100"
    }
   ]
  },
  {
   "title": "收割机超时监控 (  单位：秒 )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$host_name : $plot_path ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "harvester",
     "query": "SELECT timeout, \"host\",plot_path, plot_name FROM \"chia_log_monitor\"  WHERE \"host\"='$host_name' AND \"plot_path\"='$plot_path' AND time > now() -60d",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "收割机日志监控",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "SELECT msg, node, \"host\", logger, level, plot_path, plot_name, counter FROM \"chia_log_monitor\"  where node = 'harvester' and time > now() - 60d order by time desc limit 100"
    }
   ]
  }
 ]
}